describe('InstuLearn Register Testi', () => {
  it('InstuLearn Register Testi', () => {
    // Visit the registration page
    cy.visit('https://qa.instulearn.com/');
    
    
    cy.get('#app a.mr-10').click();
    cy.get('[name="email"]').click();
    cy.get('[name="email"]').type('lazKorsan10825@gmail.com');
    cy.get('[name="password"]').click();
    cy.get('[name="password"]').type('Query.2026');
    cy.get('#app button.btn-block').click();
    
    
    cy.get('#panel-sidebar-scroll a[href="#webinarCollapse"] span.text-dark-blue').click();
    cy.get('#webinarCollapse a[href="/panel/webinars/new"]').click();
    cy.get('#webinarForm [name="type"]').select('course');
    cy.get('#webinarForm [name="title"]').click();
    cy.get('#webinarForm [name="title"]').type('Akkvaryum Bakimi');
    cy.get('#webinarForm [name="seo_description"]').click();
    cy.get('#webinarForm [name="seo_description"]').type('Akvaryum balıklarını korumak');
    cy.get('#webinarForm button[data-input="thumbnail"]').click();
    cy.get('[name="thumbnail"]').click();
    cy.get('[name="thumbnail"]').type('asd');
    cy.get('[name="image_cover"]').click();
    cy.get('[name="image_cover"]').type('a');
    cy.get('[name="image_cover"]').type('sdf');
    cy.get('#webinarForm div.card-block').click();
    cy.get('#webinarForm div.card-block').clear();
    cy.get('#webinarForm div.card-block').type('Akvaryum balıklarının sağlıklı bir şekilde gelişimlerini surdurabilmeleiri için gerekkli testnik destek sağlanır ');
    cy.get('#getNextStep').click();
    cy.get('#webinarForm [name="capacity"]').click();
    cy.get('#webinarForm [name="capacity"]').type('42');
    cy.get('#webinarForm [name="duration"]').click();
    cy.get('#webinarForm [name="duration"]').type('45');
    cy.get('#webinarForm div:nth-child(3) > div.custom-switch > label.custom-control-label').click();
    cy.get('[name="support"]').check();
    cy.get('#webinarForm div:nth-child(4) label.custom-control-label').click();
    cy.get('[name="certificate"]').check();
    cy.get('#webinarForm div:nth-child(6) label.custom-control-label').click();
    cy.get('[name="downloadable"]').check();
    cy.get('#webinarForm div.bootstrap-tagsinput input').click();
    cy.get('#webinarForm input[size="39"]').type('oftWareEngineerin with aqua fish ');
    cy.get('#webinarForm div:nth-child(10)').click();
    cy.get('[name="category_id"]').select('613');
    cy.get('#getNextStep').click();
    cy.get('#webinarForm label.custom-control-label').click();
    cy.get('[name="subscribe"]').check();
    cy.get('#webinarForm [name="access_days"]').click();
    cy.get('#webinarForm [name="access_days"]').type('23');
    cy.get('#webinarForm [name="price"]').click();
    cy.get('#webinarForm [name="price"]').type('0');
    cy.get('#getNextStep').click();
    cy.get('#webinarForm button.js-add-chapter').click();
    cy.get('#chapterModalydOjJ [name="ajax[chapter][title]"]').click();
    cy.get('#chapterModalydOjJ [name="ajax[chapter][title]"]').type('Aqua Fish Clean Atmosphere');
    cy.get('#chapterModalydOjJ button.save-chapter').click();
    cy.get('#getNextStep').click();
    cy.get('#webinarAddPrerequisites').click();
    cy.get('#prerequisite_XbBLq').click();
    cy.get('#prerequisitesAccordion li.bg-white').click();
    cy.get('#prerequisite_XbBLq span').click();
    cy.get('#prerequisite_XbBLq span').click();
    cy.get('#select2-ajaxnewprerequisite_id-aw-container span.select2-selection__placeholder').click();
    cy.get('input.select2-search__field').type('sof');
    cy.get('#collapsePrerequisiteXbBLq button.js-save-prerequisite').click();
    cy.get('#getNextStep').click();
    cy.get('#webinarAddFAQ').click();
    cy.get('#collapseFaqhvnrB [name="ajax[new][title]"]').click();
    cy.get('#collapseFaqhvnrB [name="ajax[new][title]"]').type('beslenme periyodu ');
    cy.get('#collapseFaqhvnrB [name="ajax[new][answer]"]').click();
    cy.get('#collapseFaqhvnrB [name="ajax[new][answer]"]').type('akvaryum balıkları 2 güne bir beslenmelidr.');
    cy.get('#collapseFaqhvnrB button.js-save-faq').click();
    cy.get('#getNextStep').click();
    cy.get('#webinarAddQuiz').click();
    cy.get('#collapseQuizWlhAT [name="ajax[new][title]"]').click();
    cy.get('#collapseQuizWlhAT [name="ajax[new][title]"]').type('akvaryum balıgi beslenme usulleri');
    cy.get('#collapseQuizWlhAT [name="ajax[new][time]"]').click();
    cy.get('#collapseQuizWlhAT [name="ajax[new][time]"]').type('45');
    cy.get('#collapseQuizWlhAT [name="ajax[new][attempt]"]').click();
    cy.get('#collapseQuizWlhAT [name="ajax[new][attempt]"]').type('2');
    cy.get('#collapseQuizWlhAT [name="ajax[new][pass_mark]"]').click();
    cy.get('#collapseQuizWlhAT [name="ajax[new][pass_mark]"]').type('100');
    cy.get('#collapseQuizWlhAT [name="ajax[new][expiry_days]"]').click();
    cy.get('#collapseQuizWlhAT [name="ajax[new][expiry_days]"]').type('28');
    cy.get('#collapseQuizWlhAT div:nth-child(9) label.custom-control-label').click();
    cy.get('#displayQuestionsRandomlySwitchWlhAT').check();
    cy.get('#collapseQuizWlhAT div:nth-child(10) label.custom-control-label').click();
    cy.get('#certificateSwitchWlhAT').check();
    cy.get('#collapseQuizWlhAT div:nth-child(11) label.custom-control-label').click();
    cy.get('#statusSwitchWlhAT').check();
    cy.get('#collapseQuizWlhAT button.js-submit-quiz-form').click();
    cy.get('#sendForReview').click();
  });
});
